---
apiVersion: v1
kind: Service
metadata:
  name: wuserver
spec:
  ports:
    - name: wuserver-port
      port: 10000
      protocol: TCP
      targetPort: wuserver-port
  selector:
    app: wuserver
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: wu-elastic
spec:
  ports:
    - name: wu-es-port
      port: 9200
      protocol: TCP
      targetPort: wu-es-port
  selector:
    app: wu-elastic
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wuserver
  labels:
    app: wuserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wuserver
  template:
    metadata:
      name: wuserver
      labels:
        app: wuserver
    spec:
      containers:
        - name: wuserver
          image: mas9612/wrapups:v0.4
          args:
            - --elastic-addr
            - wu-elastic
          ports:
            - name: wuserver-port
              containerPort: 10000
              protocol: TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wu-es-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-nfs-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wu-elastic
  labels:
    app: wu-elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wu-elastic
  template:
    metadata:
      name: wu-elastic
      labels:
        app: wu-elastic
    spec:
      containers:
        - name: wu-elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
          ports:
            - name: wu-es-port
              containerPort: 9200
              protocol: TCP
          volumeMounts:
            - name: wu-es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: wu-es-data
          persistentVolumeClaim:
            claimName: wu-es-data
