- name: Install epel repository
  yum:
    name: epel-release
  when: ansible_distribution == "CentOS"

- name: Update all packages
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install base packages
  yum:
    name: "{{ item }}"
  with_items:
    - chrony
    - firewalld
    - vim
  when: ansible_distribution == "CentOS"

- name: Install SELinux Library
  yum:
    name: libselinux-python
  when: ansible_selinux != false

- name: Copy chrony.conf
  copy:
    src: templates/chrony.conf
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "CentOS"

- name: Start and Enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - chronyd.service
    - firewalld.service
  when: ansible_distribution == "CentOS"

# TODO: Install node_exporter latest version
