- name: Update all packages
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install base packages
  yum:
    name: "{{ item }}"
  with_items:
    - firewalld
    - vim
    - git
  when: ansible_distribution == "CentOS"

- name: Install SELinux Library
  yum:
    name: libselinux-python
  when: ansible_selinux != false

- name: Start and Enable firewalld
  systemd:
    name: firewalld.service
    daemon_reload: yes
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS"

- name: firewalld - Allow ssh only from internal network
  firewalld:
    rich_rule: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 'rule family=ipv4 source address="10.1.0.0/16" service name=ssh accept'
  when: ansible_distribution == "CentOS"

- name: firewalld - Delete ssh rule
  firewalld:
    service: ssh
    permanent: true
    immediate: yes
    state: disabled
  when: ansible_distribution == "CentOS"

- name: firewalld - Reload (To reflect changes)
  shell: firewall-cmd --reload
  when: ansible_distribution == "CentOS"
