- name: install IUS release package
  yum:
    name: "https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm"
    state: present
  tags:
    - python3
  when: ansible_distribution == "CentOS"
  # when: ansible_os_family == 'RedHat'
  #
- name: Install Python3
  yum:
    name:
      - python36u
      - python36u-pip
      - python36u-setuptools
  tags:
    - python3
  when: ansible_distribution == "CentOS"

- name: Install ansible
  shell: pip3.6 install ansible
  tags:
    - python3
  when: ansible_distribution == "CentOS"
