- name: Install BIND
  yum:
    name:
      - bind
      - bind-utils
  tags:
    - dns
  when: ansible_distribution == "CentOS"

- name: Copy config files
  copy:
    src:  "{{ item.src }}"
    dest:  "{{ item.dest }}"
    mode: 0644
    owner: root
    group: named
  with_items:
    - {'src': 'named.conf', 'dest': '/etc/named.conf'}
    - {'src': 'db.k800123.firefly.kutc.kansai-u.ac.jp', 'dest': '/var/named/db.k800123.firefly.kutc.kansai-u.ac.jp'}
    - {'src': 'db.192.168.97', 'dest': '/var/named/db.192.168.97'}
    - {'src': 'db.192.168.100', 'dest': '/var/named/db.192.168.100'}
    - {'src': 'db.192.168.101', 'dest': '/var/named/db.192.168.101'}
    - {'src': 'db.10.1.240', 'dest': '/var/named/db.10.1.240'}
    - {'src': 'db.127.0.0', 'dest': '/var/named/db.127.0.0'}
  notify:
    - named-checkconf
    - reload named
  tags:
    - dns
  when: ansible_distribution == "CentOS"

- name: Allow dns service port
  firewalld:
    service: dns
    permanent: yes
    immediate: yes
    state: enabled
  tags:
    - dns
  when: ansible_distribution == "CentOS"

- name: Start and Enable bind
  systemd:
    name: named
    daemon_reload: yes
    enabled: yes
    state: started
  tags:
    - dns
  when: ansible_distribution == "CentOS"
