---
apiVersion: v1
kind: Service
metadata:
  name: authserver
spec:
  ports:
    - name: authserver-port
      port: 10000
      protocol: TCP
      targetPort: authserver-port
  selector:
    app: authserver
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      name: authserver
      labels:
        app: authserver
    spec:
      containers:
        - name: authserver
          image: mas9612/authserver:latest
          args:
            - --ldap-addr
            - 10.1.3.21
            - --user-format
            - "uid=%s,ou=Users,dc=ldap,dc=firefly,dc=kutc,dc=kansai-u,dc=ac,dc=jp"
            - --pem
            - /app/authserver.pem
            - --issuer
            - authserver.k800123.firefly.kutc.kansai-u.ac.jp
          ports:
            - name: authserver-port
              containerPort: 10000
              protocol: TCP
          volumeMounts:
            - name: authserver-signkey
              readOnly: true
              mountPath: /app/authserver.pem
              subPath: authserver.pem
      volumes:
        - name: authserver-signkey
          secret:
            secretName: authserver-signkey
