- hosts: test-k8s-master
  roles:
    - common
    - docker
    - nfs-client
    - k8s-node
    - k8s-master

- hosts: prod-k8s-master
  roles:
    - common
    - docker
    - nfs-client
    - k8s-node
    - k8s-master

- hosts: test-k8s-worker
  roles:
    - common
    - docker
    - nfs-client
    - k8s-node
    - k8s-worker

- hosts: prod-k8s-worker
  roles:
    - common
    - docker
    - nfs-client
    - k8s-node
    - k8s-worker
