- name: Copy firewalld service files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - {'src': 'templates/apiserver.xml', 'dest': '/etc/firewalld/services/apiserver.xml'}
    - {'src': 'templates/etcd.xml', 'dest': '/etc/firewalld/services/etcd.xml'}
    - {'src': 'templates/kube-controller-manager.xml', 'dest': '/etc/firewalld/services/kube-controller-manager.xml'}
    - {'src': 'templates/kube-scheduler.xml', 'dest': '/etc/firewalld/services/kube-scheduler.xml'}
  tags:
    - k8s-master
  when: ansible_distribution == "CentOS"

- name: firewalld - Reload
  shell: firewall-cmd --reload
  tags:
    - k8s-master
  when: ansible_distribution == "CentOS"

- name: firewalld - Allow master services
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: yes
    state: enabled
  with_items:
    - "apiserver"
    - "etcd"
    - "kube-controller-manager"
    - "kube-scheduler"
  tags:
    - k8s-master
  when: ansible_distribution == "CentOS"
