apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.100.1
      peer-asn: 65004
      my-asn: 65110
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.101.0/24
